### ISSUE TITLE
bug in create_eulerian_circuit

### ISSUE THREAD

**Issue by brooksandrew** [brooksandrew/postman_problems#43]
Bug when we use this star graph

```
n_nodes=10

def create_star_graph(n_nodes=10, ring=True):
    """
    Create a star graph with the points connected by
    Args:
        n_nodes (int): number of nodes in graph
        ring (Boolean): add ring around the border with low (distance=2) weights

    Returns:
        networkx graph in the shape of a star

    """
    graph = nx.MultiGraph()
    node_names = list(string.ascii_lowercase)[:n_nodes]
    graph.add_star(node_names)
    nx.set_edge_attributes(graph, 10, 'distance')
    nx.set_edge_attributes(graph, 1, 'required')
    nx.set_edge_attributes(graph, 'solid', 'style')
    if ring:
        for e in list(zip(node_names[:-1], node_names[1:])):
            graph.add_edge(e[0], e[1], distance=2, required=0, style='dashed')
    return graph
```

### Error

The following are printed below at the bottom of each iteration of the `for edge in euler_circuit:` loop
        print(edge)
        print(possible_edges)
        print(edge_key)

```
('a', 'j')
[('a', 'j', {'distance': 10, 'required': 1, 'style': 'solid', 'id': 9})]
0
('j', 'i')
[('i', 'j', {'distance': 2, 'augmented': True})]
0
('i', 'a')
[('a', 'i', {'distance': 10, 'required': 1, 'style': 'solid', 'id': 8})]
0
('a', 'h')
[('a', 'h', {'distance': 10, 'required': 1, 'style': 'solid', 'id': 7})]
0
('h', 'g')
[('g', 'h', {'distance': 2, 'augmented': True})]
0
('g', 'a')
[('a', 'g', {'distance': 10, 'required': 1, 'style': 'solid', 'id': 6})]
0
('a', 'f')
[('a', 'f', {'distance': 10, 'required': 1, 'style': 'solid', 'id': 5})]
0
('f', 'e')
[('e', 'f', {'distance': 2, 'augmented': True})]
0
('e', 'a')
[('a', 'e', {'distance': 10, 'required': 1, 'style': 'solid', 'id': 4})]
0
('a', 'd')
[('a', 'd', {'distance': 10, 'required': 1, 'style': 'solid', 'id': 3})]
0
('d', 'c')
[('c', 'd', {'distance': 2, 'augmented': True})]
0
('c', 'a')
[('a', 'c', {'distance': 10, 'required': 1, 'style': 'solid', 'id': 2})]
0
('a', 'b')
[('a', 'b', {'distance': 10, 'required': 1, 'style': 'solid', 'id': 0}), ('a', 'b', {'distance': 1, 'augmented': True})]
0
('b', 'a')
[('a', 'b', {'distance': 1, 'augmented': True})]
1
Traceback (most recent call last):
  File "postman_problems/examples/star/rpp_star.py", line 93, in <module>
    main()
  File "postman_problems/examples/star/rpp_star.py", line 58, in main
    circuit, graph = rpp(edgelist_file, start_node=START_NODE)
  File "/Users/ajb/Documents/github/postman_problems/postman_problems/graph.py", line 353, in rpp
    circuit = list(create_eulerian_circuit(g_aug, g_full, start_node))
  File "/Users/ajb/Documents/github/postman_problems/postman_problems/graph.py", line 229, in create_eulerian_circuit
    edge_data.remove(possible_edges[edge_key])
IndexError: list index out of range

```

**Comment by brooksandrew** [comment]
fixed w https://github.com/brooksandrew/postman_problems/pull/45
